driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux

suites:
  # this tests basic functionality
  - name: default
    run_list:
      - recipe[unit::default]
    attributes:
  # this tests that we can run inside an LWRP
  - name: lwrp
    run_list:
      - recipe[unit::lwrp]
    attributes:
  # this tests that we can run inside a resource
  - name: resource
    run_list:
      - recipe[unit::resource]
    attributes:
