---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.1.2"

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: freebsd-11.0
  - name: fedora-25
  - name: debian-7.11
  - name: debian-8.6
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  # this tests basic functionality
  - name: default
    run_list:
      - recipe[unit::default]
    attributes:
  # this tests that we can run inside an LWRP
  - name: lwrp
    run_list:
      - recipe[unit::lwrp]
    attributes:
  # this tests that we can run inside a resource
  - name: resource
    run_list:
      - recipe[unit::resource]
    attributes:
